version: "2.4"
services:
   slate-app:
     restart: always
     image:  ssanj/slate-scrib@sha256:77ef9e968752dfa7f9f8bd3f353104fa98a1127c3158999b8fa66b325494df90
     container_name: slate-app
     ports:
        - 3000:3000
     volumes:
       - "./volumes/slate-app/db:/app/db"
     environment:
       # - VIRTUAL_HOST=
       # - VIRTUAL_NETWORK=nginx-proxy
       # - VIRTUAL_PORT=3000
       # - LETSENCRYPT_HOST=
       # - LETSENCRYPT_EMAIL=
       - SLATE_API_KEY=YOUR_API_KEY
