version: "2.4"
services:
   slate-app:
     restart: always
     image:  ssanj/slate-scrib@sha256:c79a04d978ecb7b7ce8285d1b0c281111516aeaa6be13e88481ee9ebb81401b6
     container_name: slate-app
     ports:
        - 3000:3000
     volumes:
       - "./volumes/slate-app/db:/app/db"
     environment:
       # - VIRTUAL_HOST=
       # - VIRTUAL_NETWORK=nginx-proxy
       # - VIRTUAL_PORT=3000
       # - LETSENCRYPT_HOST=
       # - LETSENCRYPT_EMAIL=
       - SLATE_API_KEY=YOUR_API_KEY
