version: "2.4"
services:
   slate-app:
     restart: always
     image:  $DOCKER_IMAGE
     container_name: slate-app
     ports:
        - 5000:3000
     volumes:
       - "./volumes/slate-app/db:/app/db"
     environment:
       # - VIRTUAL_HOST=
       # - VIRTUAL_NETWORK=nginx-proxy
       # - VIRTUAL_PORT=3000
       # - LETSENCRYPT_HOST=
       # - LETSENCRYPT_EMAIL=
       - SLATE_API_KEY=YOUR_API_KEY
