CREATE TABLE IF NOT EXISTS SCRIB(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  MESSAGE TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  VERSION INT DEFAULT 1 NOT NULL
);

CREATE INDEX IDX_MESSAGE ON SCRIB(MESSAGE);
CREATE INDEX IDX_CREATED_AT ON SCRIB(CREATED_AT);
CREATE INDEX IDX_UPDATED_AT ON SCRIB(UPDATED_AT);
